---
title: "Plotly Plot"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(wesanderson)
library(ggplot2)
```

```{r, include = FALSE, message = FALSE, echo = FALSE}
homicides_data = read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/police-killings/police_killings.csv") %>%
  janitor::clean_names()

homicides_data = homicides_data %>%
  mutate(month = factor(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.integer(year))
```

Column {data-width=1000}
-----------------------------------------------------------------------

### Cumulative Killings in Each State

```{r, echo = FALSE}
homicides_plot = homicides_data %>%
  group_by(state, month) %>% 
  summarise(total_killed = n()) %>% 
  mutate(total_killed = cumsum(total_killed)) %>%
  ggplot(aes(x = month, y = total_killed, color = state)) +
  geom_point(alpha = 0.5)

ggplotly(homicides_plot)
```

----------------------------------------------------------------------
Interact with the plot above to see the cumulative number of killings in each state during the time period provided in the dataset. This information can show which months have the biggest jumps in killings. In the future, we would like to examine and see if the trends stay consistent year to year for each state. 
----------------------------------------------------------------------