---
title: "Police Killings Proposal"
date: "November 7, 2018"
output: github_document
---

Nathalie Fadel (nf2429)
Chirag Shah (cs3652)
Jeanette Shekelle (jes2353)
Jaclyn Verity (jv2629)

How Police Killings are Distributed in America

The motivation for this project is to investigate police killings in the US. Final products include visualizations of police killings by poverty level, racial/ethnic group, age, state, and whether the victim was armed or not. The anticipated data source is from the American Community Survey of 2015. We plan to analyze the peaks of police killings over time (2015). One coding challenge would be if we need to merge datasets, it may be hard to match on variables, although our datasets contains FIPS codes which may make it easier if we use other data with FIPS codes. The final products for this assignment will include exploratory analysis to decipher the overall trends seen in the data, a dashboard to illustrate the key findings related to the analysis conducted, some sort of map to show where police killings are localized, a screencast of our project, and a website that will house all of these deliverables.  

Timeline
November 11: Exploratory Data Analysis 
November 12-16: Project Review Meeting with TA
November 26: Visualizations for the following variables:
		Nathalie: Date and police killings
		Jaci: Looking at 3-4 cities in depth
		Chirag: State, Race/Ethnicity, somehow incorporate age (maybe stratify police killings by age vs/and/or poverty)
Jeanette: policy killings and income/poverty
December 2: Written report completed
December 3: Screencast meeting to record
December 6: DUE! Do peer assessment

