---
title: "Time-dependent analysis"
author: "Nathalie Fadel"
date: "11/30/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

#Data import and cleaning  
```{r}

raw_data = read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/police-killings/police_killings.csv") %>%
  janitor::clean_names()

clean_data = raw_data %>%
  mutate(month = factor(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.integer(year))

clean_data %>%
  group_by(month) %>%
  summarise(total_killed = n()) %>%
  ggplot(aes(x = month, y=total_killed)) +
  geom_col(size = 3) +
  labs(x = "Month", y = "number", 
       caption = "number of police killings by month, Jan-June 2015") 

date_data = clean_data %>%
  mutate(month = as.integer(month)) %>%
  mutate(date = paste(month, day, year, sep = "-")) %>%
  mutate(date = as.Date(date, "%m-%d-%Y"))

date_data %>%
  group_by(date) %>%
  summarise(total_killed = n()) %>%
  ggplot(aes(x = date, y=total_killed)) +
  geom_line(size = 0.5) +
  labs(x = "date", y = "number", 
       caption = "number of police killings over time, Jan-June 2015")

```


#Plan:
- Geom_point plot of killings in y axis vs time in x axis
- Date w highest number of killings (or month), location(s) in which they occurred
- Density plot of killings over time
- Map of killings w date
- If counties/states have multiple, single these out
